import Head from 'next/head'
import Layout from './components/layout/layout';
import React from 'react';
import SimpleLogin from './components/simpleLogin/simpleLogin';
import SimpleSignup from './components/simpleLogin/simpleSignup';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SimpleLogin />
        <SimpleSignup />
    </Layout>
    </>
  )
}
